// This is not a file installed from npm, this was generated by prisma.
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient({
  // To obtain all info from the queries.
  // log: process.env.NODE_ENV === "development" ? ["query", "info", "warn"] : [],
  // It is probably a good idea to save on resources and not spam the queries on the server in production.
  log: ["query", "info", "warn"],
});

// yarn db:generate comes last after a migration is finished.
// First there was creating a migration with db:migrate:new.
// then db:migrate:up to create the actual migration itself.
// then db:generate to establish updated types for PrismaClient from @prisma/client.
// Need to use PrismaClient for typing, just don't use it as a constructor again, because that was done for prisma.

export { prisma, PrismaClient };
